services:
  - type: web
    name: desafio-afya-api
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: afya-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    buildCommand: npm run build
    startCommand: npm start

databases:
  - name: afya-db
    plan: free
    databaseName: afya_db
    user: admin
